language: python
python:
  - 2.7
env:
  global:
    - APP_NAME=flaskr
    - PROD_ENVIRONMENT_NAME=flaskr-prod
    - secure: GuQ1IxuwcU7eLwzDA8zn6Xuea0XpDmBH9Pu/jeJrewaB4SypFv313ALpj5T7E22jZCh2t76IlAk5X0AHBLsgDWWv1ufnjUXQrnjPHrMifhcgp4nRTOOcFJLvVQZQOzWFJJohm6Tq4LqnDXgqA4Zc8abAmEU7OfRIjJ3LPRaL4kg=
    - secure: gATUbdF15YMERnj6mYVCoRwnZuWwsEmPXFf2vSoKjETowRn8hVE9+49hFup9VRJDl/hda31POMcy9NOnw05l3ihR8I2l8dFR6iLOLEzsLNZ+6y1VDbIodaXputWIEsoDZ6qgAZDRDpQmaQnGR53Q+BPQC3oufm0TATZp6z+iJnA=
    - secure: Cs52Td+oB8i8jO5qc2T0MC6UJT1XK7Hk4HdhYIPYiXV7XY0hBnnemN/UaDzeaGRhqoq3QZB/06D18NdooKuhSN9YnRFBKBjA0RW5kjC0ChIdsJYzZs4IBY8JDtQ1u83UhJYx1D4OCpuiLhkdyydAYPTtyXbaCryiI0PoXxFsd6A=
    - secure: NYQKtVYzERTVKjk77I9vFCaPo+ZQUm8+3KOKv+qzq9Kawl8I2AKQ47/Tf5nUXc1t/n+h91RcDXAa8hsKH/zK2aibB6kR4Y+VimEK6/TepmkjT1sPZhojfmfMypy3LA2nwowbKjV3EMZYFnj7RCixwCvCkhJ5WciiGprPl9vO+4E=
addons:
  sauce_connect: true
# command to install dependencies
install:
  - sudo curl https://s3-us-west-1.amazonaws.com/bp-public/utilities/bigpanda-deployment -o /usr/local/bin/bigpanda-deployment
  - sudo chmod a+x /usr/local/bin/bigpanda-deployment
  - pip install https://github.com/mitsuhiko/flask/tarball/master
  - pip install selenium pytest pytest-xdist sauceclient mixpanel-py
  - pip install newrelic
# command to run tests
before_script:
  - BP_API_TOKEN=c07b745b5db330137f62e44ce385090f bigpanda-deployment start $APP_NAME $TRAVIS_BUILD_NUMBER travishost
  - curl -H "x-api-key:c597e794ac5a48292c68c3149c1fe38ce55ec9ff00bd690" -d "deployment[app_name]=Flaskr" -d "deployment[revision]=$TRAVIS_BUILD_NUMBER" https://api.newrelic.com/deployments.xml
  - sqlite3 /tmp/flaskr.db < schema.sql
script:
  - flask --app=flaskr initdb
  - newrelic-admin run-program flask --app=flaskr run
  #- flask --app=flaskr run &> flask.log &
  - py.test -n5 --boxed test_login.py

after_success:
  - BP_API_TOKEN=c07b745b5db330137f62e44ce385090f bigpanda-deployment success $APP_NAME $TRAVIS_BUILD_NUMBER travishost

after_failure:
  - BP_API_TOKEN=c07b745b5db330137f62e44ce385090f bigpanda-deployment fail $APP_NAME $TRAVIS_BUILD_NUMBER travishost
