language: python
python:
  - 2.7
# command to install dependencies
install:
  - pip install flask
  - pip install selenium
  - pip install python-wd-parallel
# command to run tests
before_script:
  - sqlite3 /tmp/flaskr.db < schema.sql
script:
  - flask --app=flaskr initdb
  - flask --app=flaskr run
  - python test_login.py