language: python
python:
  - 2.7
# command to install dependencies
install:
  - pip install flask
  - pip install selenium
  - pip install python-wd-parallel
# command to run tests
before_script:
  - sqlite3 /tmp/flaskr.db < schema.sql
script:
  - python flaskr.py
  - python test_login.py